name: test-cluster
namespace: clusters
providerDomain: "" # optional
publicDomain: ""
publicZoneID: ""
privateZoneID: ""
oidcURL: ""
etcdEncryptionKey: "" # value should be base64 encoded
vpcID: ""
vpcCidrBlocks: []
subnetID: ""
zone: ""
region: ""
pullSecret: "hypershift-pull-secret"
sshKey: "hypershift-ssh-key"
releaseImage: "quay.io/openshift-release-dev/ocp-release:4.14.10-multi-x86_64"
fipsEnabled: false
oauthEndpointCertificateSecretName: ""

roles:
  controlPlaneOperator: ""
  imageRegistry: ""
  ingress: ""
  cloudController: ""
  network: ""
  nodePool: ""
  storage: ""

workers:
  replicas: 1
  instanceType: "t3a.xlarge"
  profile: ""
  securityGroup: ""
  autoscaling:
    enabled: false
    max: 0
    min: 0
  arch: "amd64"

vault:
  roleID: ""
  secretID: ""

# github:
#   clientID: ""
#   clientSecret: ""
#   teams: []

managedClusterSet: ""
managedClusterExtraLabels: []

tolerations: []
nodeSelector: []
